spring:
  datasource:
    url: postgres://jtrnwzyinpihkv:456643e01c653aab9c18e2f746727c9b2452ec596cfbb214ac79efe0f9b1496e@ec2-44-198-151-32.compute-1.amazonaws.com:5432/dd9vg9lcft0sg2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
bluefood:
  files:
    logotipo: src/main/resources/static/image/logotipo
    comida: src/main/resources/static/image/comida
    categoria: src/main/resources/static/image/categoria


      #url: jdbc:mysql://localhost:3306/javafood?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      #username: root
    #password:

#      driver-class-name: org.postgresql.Driver