spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluefooddb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
bluefood:
  files:
    logotipo: C:/Users/Leonardo/Documents/images/logotipo
    comida: C:/Users/Leonardo/Documents/images/comida
    categoria: C:/Users/Leonardo/Documents/images/categoria


