spring:
  datasource:
    url: postgres://poiofxfulhbsdp:5af5b9ed103b555f81d67fa8cb16fd75d075f5aa6eb2ac91600f2e458860c242@ec2-34-227-120-94.compute-1.amazonaws.com:5432/dflmk8j9fcsma4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
bluefood:
  files:
    logotipo: src/main/resources/static/image/logotipo
    comida: src/main/resources/static/image/comida
    categoria: src/main/resources/static/image/categoria


      #url: jdbc:mysql://localhost:3306/javafood?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      #username: root
    #password:

#      driver-class-name: org.postgresql.Driver