spring:
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
bluefood:
  files:
    logotipo: src/main/resources/static/image/logotipo
    comida: src/main/resources/static/image/comida
    categoria: src/main/resources/static/image/categoria



    #url: jdbc:mysql://localhost:3306/javafood?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      #username: root
      #password: