spring:
  datasource:
    url: postgres://wdcibsxayabkji:e9708500ccee4d31de6b5eb807d82181f7be0059110547a87eef818abaf94e93@ec2-44-198-151-32.compute-1.amazonaws.com:5432/d9hjoorcjqffbe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
bluefood:
  files:
    logotipo: src/main/resources/static/image/logotipo
    comida: src/main/resources/static/image/comida
    categoria: src/main/resources/static/image/categoria


      #url: jdbc:mysql://localhost:3306/javafood?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      #username: root
    #password:

#      driver-class-name: org.postgresql.Driver