spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluefooddb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

bluefood:
  files:
    logotipo: C:/Users/Leonardo/Documents/images



